baseurl = "https://www.coxbridge.net/"
languageCode = "en-us"
title = "Team Coxbridge"
theme = "strata"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Coxbridge"
  description = '''Rowing coach in Cambridge, UK. Working with clubs and
  individual rowers.'''

  # Format dates with Go's time formatting
  date_format = "2006-01-02"

  # Add read time estimates in the format "X min read"
  show_read_time = false

  # Add custom assets with their paths relative to the static folder
  custom_js   = []
  custom_css  = []


  [params.sidebar]
    # Replace the avatar with a picture of your own under static/images
    avatar = "thumbs/coxbridge-01.jpg"
    # Use Markdown to format the string. This works nearly all over the
    # theme
    bio = '''I am Silvia Breu of **Team Coxbridge**, a team of rowing coaches in Cambridge. Together we make crews row faster.'''

    # The icons will be shown if you enter your username
    twitter     =  "coxbridge"
    github      =  ""
    gitlab      =  ""
    dribbble    =  ""
    facebook    =  ""
    googleplus  =  ""
    flickr      =  ""
    linkedin    =  ""
    copyright = [
      "&copy; 2018, Silvia Breu",
      "Design: [HTML5 UP](//html5up.net)"
    ]


  [params.about]
    hide  = false
    title = "Rowing Coach"
    content = '''Team Coxbridge helps individuals and crews to reach
    their goals, and beyond, in rowing. We work with college and town
    clubs, as well as individual rowers. This includes land and water
    training, technical and performance training, for a season or for
    finishing touches before a race. We are based in Cambridge but
    have run training camps as far aways as in China.
    '''

  [params.portfolio]
    hide  = false
    title = "Impressions"

    # The images and thumbnails are stored under static/images
    # Create and change subfolders as you like
    [[params.portfolio.gallery]]
      image = "fulls/coach-201.jpg"
      thumb = "thumbs/coach-thumb-201.jpg"
      title = "Coaching on the towpath"
      description = "Coaching on the towpath"

    [[params.portfolio.gallery]]
      image = "fulls/coxbridge-03.jpg"
      thumb = "thumbs/coxbridge-03.jpg"
      title = "Working with ARU M1 during May Bumps"
      description =  "Working with ARU M1 during May Bumps"

    [[params.portfolio.gallery]]
      image = "fulls/coxbridge-04.jpg"
      thumb = "thumbs/coxbridge-04.jpg"
      title = "Bumped!"
      description = "Bumped!"

    [[params.portfolio.gallery]]
      image = "fulls/coxbridge-06.jpg"
      thumb = "thumbs/coxbridge-06.jpg"
      title = "Churchill College Boat Club M1"
      description =  "Churchill College Boat Club M1"

    [[params.portfolio.gallery]]
      image = "fulls/coxbridge-10.jpg"
      thumb = "thumbs/coxbridge-10.jpg"
      title = "Churchill College Boat Club"
      description = "Churchill College Boat Club"

    [[params.portfolio.gallery]]
      image = "fulls/coxbridge-09.jpg"
      thumb = "thumbs/coxbridge-09.jpg"
      title = "Blade CUWBC vs. OUWBC"
      description = "Blade"

    [[params.portfolio.gallery]]
      image = "fulls/coxbridge-08.jpg"
      thumb = "thumbs/coxbridge-08.jpg"
      title = "X-Press Boat Club"
      description = "X-Press Boat Club"

    [[params.portfolio.gallery]]
      image = "fulls/coxbridge-05.jpg"
      thumb = "thumbs/coxbridge-05.jpg"
      title = "Sidney Sussex W1 during May Bumps"
      description = "Sidney Sussex W1"



  [params.recentposts]
    hide  = true
    title = "Recent News"

  [params.twitter]
    hide  = false
    account = "coxbridge"

  [params.results]
    hide = false
    title = "Selected Results and Activities"
    content = '''

* [Wolfson College Boat Club] M1 won blades at May Bumps 2016, W1 won
  blades at Lent Bumps 2017 and May Bumps 2017.
* [Sidney Sussex Boat Club] M1 won blades at May Bumps 2017 (hadn't
  happened in 22 years).
* [Churchill College Boat Club] M1
  won super blades in Lent Bumps 2015 and blades in Lent Bumps 2016 in
  Division 1.
* [Churchill College Boat Club]: One-week training camp at
  [Molesey Boat Club] for M1, M2, and W1 in 2015, 2016, 2017.
* Heach Coach of Deep Dive Junior Rowing Programe in China, 2015.
* [Cambridge University Lightweight Rowing Club] (Assistant Coach):
  Winner of the Boat Race against Oxford OULRC in 2014 and 2015.
* [Anglia Ruskin Boat Club] W1 won blades at Cambridge May Bumps
  2014.

[Cambridge University Lightweight Rowing Club]: http://www.culrc.org.uk
[Churchill College Boat Club]: http://www.churchillboatclub.org.uk
[Anglia Ruskin Boat Club]: https://www.anglia.ac.uk/sport/sports/rowing
[Molesey Boat Club]: https://www.moleseyboatclub.co.uk
[Wolfson College Boat Club]: https://www.wolfson.cam.ac.uk/boatclub
[Sidney Sussex Boat Club]: http://ssbc.org.uk
'''

  [params.licenses]
    hide = false
    title = "Licenses and Memberships"
    content = '''
* [British Rowing] Level 2 Coaching License 
* Member of [British Rowing]
* DBS check for working with children
* Launch Driving --- Power Boat Level 2  
* Radio License
* Driving License including for towing: B, B+E, C1 

[British Rowing]: http://britishrowing.org
'''


  [params.contact]
    hide  = false
    title = "Get In Touch"
    content = '''You can always talk to me on the towpath or send me an
    email --- directly or using the form below.'''

    # This can be exact coordinates or a searchable address in google maps
    gmaps_address = "52.211373, 0.139495"
    address = [
      "Cambridge",
      "UK"
    ]
    # phone = "000-000-0000"

    # Since this template is static, the contact form uses
    # www.formspree.io as a proxy. The form makes a POST request to
    # their servers to send the actual email. Visitors can send up to a
    # 1000 emails each month for free.
     
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below - upload the
    # generated site to your server - send a dummy email yourself to
    # confirm your account - click the confirm link in the email from
    # www.formspree.io - you're done. Happy mailing!

    email = "silvia@coxbridge.net"

    [params.contact.form]
      # Set custom strings for the form if your native
      # language isn't English
      name = "Your Name"
      email = "Your Email Address"
      message = "Message for Silvia"
      submit = "Send Message"


# Menu links that appear on the left sidebar
[[menu.main]]
  name = "Home"
  url  = "/index.html"
  weight = 10

# [[menu.main]]
#  name = "News"
#  url  = "post/"
#  weight = 0
